# Generated by Django 6.0.2 on 2026-02-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_character'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='background',
            new_name='background_image',
        ),
    ]
